#!/usr/bin/env bash
# ai/init.sh - Bootstrap script for agent-foreman harness
# Generated by agent-foreman
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Bootstrap: Install dependencies
bootstrap() {
  log_info "Installing dependencies..."
  pnpm install
  log_info "Bootstrap complete!"
}

# Dev: Start development environment
dev() {
  log_info "Starting development server..."
  pnpm dev
}

# Check: Delegate to agent-foreman check for unified verification
# All verification logic is centralized in agent-foreman check
# Usage: check [task_id] [--ai] [--full] [--verbose]
check() {
  # Check if agent-foreman is available
  if ! command -v agent-foreman &> /dev/null; then
    log_error "agent-foreman not found. Install with: npm install -g agent-foreman"
    exit 1
  fi

  log_info "Running verification via agent-foreman..."
  agent-foreman check "$@"
}

# Build: Build for production
build() {
  log_info "Building for production..."
  echo 'No build command configured'
  log_info "Build complete!"
}

# Status: Show project status
status() {
  log_info "Project Status"
  echo "---"

  # Show feature list status if exists (check new format first, then legacy)
  if [ -f "ai/tasks/index.json" ]; then
    echo "Task Index: ai/tasks/index.json"
    local total=$(jq '.features | keys | length' ai/tasks/index.json)
    local passing=$(jq '[.features | to_entries[] | select(.value.status == "passing")] | length' ai/tasks/index.json)
    local failing=$(jq '[.features | to_entries[] | select(.value.status == "failing")] | length' ai/tasks/index.json)
    local review=$(jq '[.features | to_entries[] | select(.value.status == "needs_review")] | length' ai/tasks/index.json)
    echo "  Total: $total"
    echo "  Passing: $passing"
    echo "  Failing: $failing"
    echo "  Needs Review: $review"
  elif [ -f "ai/feature_list.json" ]; then
    echo "Feature List (legacy): ai/feature_list.json"
    local total=$(jq '.features | length' ai/feature_list.json)
    local passing=$(jq '[.features[] | select(.status == "passing")] | length' ai/feature_list.json)
    local failing=$(jq '[.features[] | select(.status == "failing")] | length' ai/feature_list.json)
    local review=$(jq '[.features[] | select(.status == "needs_review")] | length' ai/feature_list.json)
    echo "  Total: $total"
    echo "  Passing: $passing"
    echo "  Failing: $failing"
    echo "  Needs Review: $review"
  else
    log_warn "No feature list found. Run 'agent-foreman init' first."
  fi

  # Show recent progress log entries
  if [ -f "ai/progress.log" ]; then
    echo ""
    echo "Recent Progress:"
    tail -5 ai/progress.log
  fi
}

# Help
show_help() {
  echo "Usage: ./ai/init.sh <command> [options]"
  echo ""
  echo "Commands:"
  echo "  bootstrap             Install dependencies"
  echo "  dev                   Start development server"
  echo "  check [task_id]       Run verification (delegates to agent-foreman check)"
  echo "    (no args)           Fast mode: git diff based selective tests"
  echo "    [task_id]           Task mode: verify specific task"
  echo "    --ai                Fast mode + AI verification for affected tasks"
  echo "    --full              Full verification (all tests + build + E2E)"
  echo "    --verbose, -v       Show detailed output"
  echo "  build                 Build for production"
  echo "  status                Show project status"
  echo "  help                  Show this help message"
}

# Main entry point
case "${1:-help}" in
  bootstrap)
    bootstrap
    ;;
  dev)
    dev
    ;;
  check)
    shift
    check "$@"
    ;;
  build)
    build
    ;;
  status)
    status
    ;;
  help|--help|-h)
    show_help
    ;;
  *)
    log_error "Unknown command: $1"
    show_help
    exit 1
    ;;
esac
